chandra_aca/plot.py
Did any of the example plots ever show a fid light?  The line is too thin and there is no `+` to mark the spot.
=> More closely reproduce the starcheck fid symbol

chandra_aca/__init__.py, chandra_aca/star_probs.py
See 2016x02x03 star working group for related notes.
This defaults to use the old (MS flag enabled) calibration, so it is back-compatible.  Starcheck would need code to specifically change the setting: `star_probs.set_fit_pars(ms_enabled=False)` for catalogs beyond FEB0816.
=> Allow for two calibration sets corresponding to MS flag enabled/disabled

chandra_aca/star_probs.py, chandra_aca/tests/test_all.py
Add ad-hoc probability adjustments for search boxes greater than 120 arcsecs.
To mitigate risk of safing action (BSH, NSM) due to observed attitude errors significantly larger than estimated attitude errors, test SAUSAGE has had had a new acquisition stage added (and one modified) to allow stage 1 stars to have up to 180 arcsec hw search boxes and stage 2 stars to have up to 160 arcsec hw search boxes.  This PR adds ad-hoc adjustments to acquisition probabilities for stars with bigger (> 120 arcsec) search boxes with the understanding that increasing the number of pixels in the box will also increase the chance that the star not be acquired due to hot pixel.   These new probabilities will be used in starcheck to review catalogs with these larger search boxes.
=> Add ad-hoc probability adjustment for larger acquisition search boxes

chandra_aca/__init__.py, chandra_aca/tests/test_all.py, chandra_aca/transform.py
This allows for exactly replicating the flight AOACYAN and AOACZAN values from telemetry without any need for arbitrary offsets.  It depends on the ACA housing temperature (AACH1T).
=> Add flight EEPROM coefficients for pixel to angle conversion

chandra_aca/attitude.py, chandra_aca/tests/test_attitude.py
This takes about 0.2 msec to compute a roll/pitch/yaw offset.
See [calc_att_validate.ipynb](http://nbviewer.jupyter.org/url/asc.harvard.edu/mta/ASPECT/ipynb/chandra_aca/calc_att_validate.ipynb) for validation plots.
=> Add functions for fast attitude determination based on star data

chandra_aca/tests/test_all.py, chandra_aca/transform.py
This is useful for the simulator, and in general for any work where raw pixel values and centroids are being interposed.  The ACA PEA uses the `edge` convention which turns out to be mostly inconvenient.  I recall worrying about this for the pipeline, and I have a vague recollection that the aspect pipeline poly coeffs are off by 2.5 arcsec because row/col there use `center`.  (That *might* be completely wrong, but that's my recollection).
In any case we need to just be clear.
=> Add pix_zero_loc param for convention on pixel labeling

chandra_aca/plot.py
Plot an ACA star field more accurately using CCD row/col as the fundamental plotting coordinates.  This makes all the critical boundaries be rectilinear on the plot, allowing for accurate visual comparison of star positions to those boundaries.
The tick marks and labels are still in yag/zag arcsec for visual reference (yag/zag is, in fact, more useful information for the viewer of the plot).  These are approximate but in most cases are within 10 arcsec (about one image pixel in the starcheck rendered PNG).
This adds a `plot_keepout` flag to enable plotting a gray area in the edge pixels where stars should not be selected.  It is False by default but should probably be enabled for starcheck.
=> Plot ACA star field more accurately using CCD row/col

chandra_aca/__init__.py, chandra_aca/aca_image.py, chandra_aca/tests/test_aca_image.py
Currently one can set row0, col0 to any number including a float (e.g. `img.row0 = np.round(..)`, which is still a float).  For recent versions of numpy slicing on floats is not allowed.
=> Cast row0, col0 vals to int

chandra_aca/aca_image.py, chandra_aca/tests/test_aca_image.py
This relies on the fact that `np.int64(5) - [1, 2, 3]` works, i.e. `np.int64(..)` will broadcast with a Python list.  Code in `annie` was accidentally working because `row0` and `col0` were `np.float64`, and so the broadcasting was working.  When `row0` was changed to `int` in #33, this broke `annie` because `int + list` fails.
=> Fix latent bug - fancy indexing did not work

chandra_aca/star_probs.py, chandra_aca/tests/test_star_probs.py
Implements update to the flight acquisition probability model:
- Include dependence on search box halfwidth
- Include data through July 2017 and fit model
Reference analysis notebooks:
-  https://github.com/sot/skanb/blob/master/pea-test-set/fit_box_size_acq_prob.ipynb
-  https://github.com/sot/aca_stats/blob/master/fit_flight_acq_prob_model.ipynb
This removes the ad-hoc model.  This obviously breaks notebooks / analysis that depend specifically on seeing the ad-hoc model.  I think this is OK, and one could always point to a local old version.
=> Update star_probs for 2017 acq prob model (search box dependence)

chandra_aca/__init__.py, chandra_aca/tests/test_star_probs.py
Update regression test values for test_halfwidth_adjustment.
It looks like the values in 3.16.1 are just incorrect.
=> Bugfix: Update test_halfwidth_adjustment expected values

chandra_aca/__init__.py, chandra_aca/tests/test_star_probs.py
Update the test to use a fixed date in acq_success_prob so that the ratios remain fixed (and the new regress values stay correct).  We could alternatively test using a larger tolerance as the ratios shouldn't change much.
=> Bugfix: Update test_halfwidth_adjustment to use fixed date 

chandra_aca/aca_image.py, chandra_aca/tests/test_aca_image.py, docs/index.rst
This requires opt-in by only doing this if one of the operands is in ACA coords, i.e. `a.aca + b` or `a + b.aca` or `a.aca + b.aca`.
```
**Initialize images (different shape and offset)**
>>> from chandra_aca.aca_image import *
>>> a = ACAImage(shape=(6, 6), row0=10, col0=20) + 1
>>> a
<ACAImage row0=10 col0=20
array([[1, 1, 1, 1, 1, 1],
[1, 1, 1, 1, 1, 1],
[1, 1, 1, 1, 1, 1],
[1, 1, 1, 1, 1, 1],
[1, 1, 1, 1, 1, 1],
[1, 1, 1, 1, 1, 1]])>
>>> b = ACAImage(np.arange(1, 17).reshape(4, 4), row0=8, col0=18) * 10
>>> b
<ACAImage row0=8 col0=18
array([[ 10,  20,  30,  40],
[ 50,  60,  70,  80],
[ 90, 100, 110, 120],
[130, 140, 150, 160]])>
**Add images (output has shape and row0/col0 of left side input)**
>>> a + b.aca
<ACAImage row0=10 col0=20
array([[111, 121,   1,   1,   1,   1],
[151, 161, …
```
=> Implement data model numerical operators using ACA coordinates

chandra_aca/__init__.py, chandra_aca/aca_image.py, chandra_aca/tests/test_psf.py
There was also a test that was accidentally passing in Py2 because the built-in round function was trying to be too helpful and converting an astropy Column of length 1 to a scalar.
=>  Do not create __div__ method in py3

chandra_aca/aca_image.py, chandra_aca/tests/test_psf.py
These two options allow `get_psf_image` to run faster:
```
In [1]: from chandra_aca.aca_image import AcaPsfLibrary
In [2]: ap = AcaPsfLibrary()
In [3]: timeit ap.get_psf_image(100.05, 200.05)
82.7 µs ± 4.45 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
In [4]: timeit ap.get_psf_image(100.05, 200.05, aca_image=False)
37 µs ± 158 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
In [5]: timeit ap.get_psf_image(100.05, 200.05, aca_image=False, interpolation='nearest')
18.6 µs ± 100 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
If or when we put this into starcheck or star selection then a factor of 4 (plus downstream speedup by using `ndarray` instead of `ACAImage`) will be important.  There is also potential for numba-izing this, though at 18 usec this …
=> Add get_psf_image options for performance-critical applications

chandra_aca/__init__.py, chandra_aca/star_probs.py, chandra_aca/tests/test_star_probs.py
Use isclose to match star colors really close to 0.700 as bad color and close to 1.5 as requiring the 1p5 model.
Closes #50
=> Use isclose to match star colors against 1.5 or 0.7

chandra_aca/tests/test_all.py, chandra_aca/transform.py
Cast everything to float64 to avoid RuntimeWarning overflows
Closes #61
=> Cast input y z in poly_convert to np.float64 to avoid overflows

chandra_aca/__init__.py, chandra_aca/drift.py, chandra_aca/tests/test_all.py
Based on the notebook in https://github.com/sot/aimpoint_mon/pull/17.   This notebook contains validation of the `chandra_aca.drift` update.
NOTE: commit 53fd2e3 will be back-ported to the `ska-legacy` branch.  All validation testing and model development was done using Ska2.  This PR also passes unit tests in Ska3 flight.
Reviewed and approved by SSAWG 2018-11-07.
=> Update drift module parameters to the 2018-11 drift model

chandra_aca/tests/test_all.py, chandra_aca/transform.py
These are thin wrappers around the corresponding Ska.quatutil methods but use arcsec instead of deg for yag, zag.  They also get away from the deprecated `in2out` naming convention and put these functions where I would expect them to be.
For 2-d or greater inputs, yagzag_to_pixels or converse would get things wrong.
Used in the above bug fix, but these are generally useful.
=> Infrastructure improvements to transform module

chandra_aca/star_probs.py, chandra_aca/tests/test_star_probs.py
This implements the SSAWG-approved change to the guide fractional counts.
Awesome tests @jeanconn!  They caught wrong things I was doing and then drove (what I think) are slight improvements in the code.  I was able to get rid of the 0.01 hack in `t_ccd_warm_limit_for_guide`.
=> Update guide_count to use linear interp not step function

chandra_aca/tests/test_all.py, chandra_aca/transform.py
This came up in starcheck / proseco development.  See also row-col-zero-location.ipynb notebook in the proseco validation dir.
=> Fix bug in check of row/col off CCD

chandra_aca/star_probs.py, chandra_aca/tests/test_star_probs.py
I got cold feet at the new linear guide_count interpolation after seeing proseco unit tests fail and realizing we still have eggs in the `guide_count` basket for ACA review of guide catalogs.  Here is the new proposed line.  This is closer to splitting the difference in the previous step-wise version.
=> Restore guide_count to be closer to previous

chandra_aca/__init__.py, chandra_aca/star_probs.py, chandra_aca/tests/test_star_probs.py
This function is what one should use to compute the confidence interval for a computed acquisition probability of `k / n` with `k` acquisition successes in `n` tries.
This also removes a couple of Py2 compatibility hooks, no longer needed for version 4.x.
=> Add function to compute binomial point percent function

chandra_aca/maude_decom.py
Of course I had to find something...
This PR makes the FID column name consistent with level0 name (IMGFID) and fixed one wrong msid.
=> FID column name

.github/workflows/build.yml
added repository_dispatch as one of the possibilities for triggering build. This is a test that needs to be in master.
=> Use repository_dispatch to trigger build

chandra_aca/tests/test_all.py
Since it was straightforward, I made this pass tests without being on VPN or the HEAD network.  When not on VPN there is one test that will take 5 seconds to time out, but that is OK.
- Ran tests both on and not on SI VPN
=> Make test_get_aimpoint work without being on VPN

chandra_aca/maude_decom.py
IMGSTAT is an unsigned 6-bit int, but the value is decom as a signed 6-bit int. This can produce negative numbers which, when cast into unsigned 32-bit int downstream, will produce numbers larger than 2^6.
Tests passed because there is no test for this failure
=> Fixed bug in decom of imgstat. It must be an unsigned int.

.github/workflows/flake8.yml, chandra_aca/dark_model.py, chandra_aca/drift.py, chandra_aca/tests/test_all.py, chandra_aca/tests/test_dark_model.py, chandra_aca/tests/test_maude_decom.py, chandra_aca/tests/test_star_probs.py
Non-controversial changes to get tests passing on shiny. The only interesting one is that comparing a table row that has an image with masked entries works with astropy 3.0 and numpy 1.12 but not in shiny. I didn't drill to the bottom of this, but in any case astropy 4.1 changes the behavior of table comparison to be more reasonable.
- [N/A] Functional testing
=> Shiny tests

.github/workflows/docs.yml, chandra_aca/maude_decom.py, docs/conf.py
This PR changes the documentation to unify style among all ska packages. Documentation is always in the docs directory, with configuration in conf.py, and uses the ska theme.
This PR also includes trivial changes for documentation:
- Escape `**kwargs` with double backticks
=> Unified documentation style

chandra_aca/centroid_resid.py
Remove check that interval is just one obsid (for obc sol).
I'm not immediately seeing a case where this would matter for the 'ground' solution but maybe I should just remove that check and allow multiple obsids there too.  Originally the idea was that the residuals object basically mapped to an obsid but I don't think we're using that much anyway, so OK if it becomes inconsistent.
Fixes #
=> Remove check that interval is just one obsid (for obc sol)

chandra_aca/planets.py, setup.py
Improve setup.py for ephemeris data download to only use standard library packages.
I removed the existing `chandra_aca/data/de432s.bsp` file and then ran `python setup.py --version` to re-download. After that I ran the unit tests with no fails.
=> Improve setup.py for ephemeris data download

chandra_aca/maude_decom.py
It turns out that assigning a masked array using row-oriented `array[idx][name]` is *extremely* slow. This one operation was completely dominating the time for doing ACA telemetry decom. This meant that the decom was much slower than fetching from MAUDE.  Instead use column oriented `array[name][idx]` and the `_aca_packets_to_table` function is 20 times faster and fetching from MAUDE is now about 60% of the time.
At the top level, this reduces the time to fetch and decom 5 minutes of telemetry from about 9 seconds to 1.6 seconds, and will thus improve the aca_view performance substantially.
I took the liberty of renaming a variable from `k` to `name` so that it is obviously a column name not an integer index.
```
In [4]: %lprun -f _aca_packets_to_table get_aca_packets('2020:003:00:31:00', …
```
=> Improve _aca_packets_to_table speed by factor of 20

chandra_aca/maude_decom.py
The astropy Table class changed behavior so that a Table can hold both MaskedColumn and Column at once. The fix here is to force all MaskedColumn with `masked=True`. 
Fixes https://github.com/sot/aca_view/issues/57
=> Fix aca_view issue 57, need masked=True in Table creation

chandra_aca/plot.py
Calculate row/col of planet even if off CCD (by using allow_bad=True in yagzag_to_pixels).
Functional test:
Allows this:
```
plot_stars([-0.45749853478319497,, 0.4309589967008305, -0.2887493342348751, 0.7222141343208118], starcat_time='2020:328:22:56:56.820', duration=10000)
``` 
to work without throwing a "ValueError: Coordinate off CCD".  I don't *think* this deserves a unit test but that's available if we want it.
=> Calculate row/col of planet even if off CCD

chandra_aca/maude_decom.py, chandra_aca/tests/test_maude_decom.py
This PR adds functionality to fetch ACA data from MAUDE blobs. The main use case is real-time viewing with aca_view (sot/aca_view/pull/65).
This PR adds the following functions to chandra_aca.maude_decom:
- **blob_to_aca_image_dict**. Convert a blob to a dict similar to the output from maude_decom.unpack_aca_telemetry
- **get_raw_aca_blobs**. Get the MAUDE blobs and group them according to the ACA packet (in groups of 4)
It modifies this function:
- **get_aca_packets**. It adds the option to get ACA telemetry from MAUDE using blobs. Does this by calling get_raw_aca_blobs, blob_to_aca_image_dict and then continues in the same way as with binary packets.
It also adds some test functions for the new functionality.
Fixes #
=> Fetch ACA telemetry from MAUDE using blobs

chandra_aca/aca_image.py, chandra_aca/tests/test_aca_image.py
`Centroid_fm` (via `_prep_6x6` inherited from annie_) was modifying the input image in place when no background was supplied.
- [n/a] Functional testing
Without the patch the updated test fails as expected.
=> Fix bug where centroid_fm was modifying input image

chandra_aca/tests/test_planets.py
Use has_internet to skip planet tests requiring network (for GRETA).
=> Use has_internet to skip planet tests requiring network

chandra_aca/tests/test_maude_decom.py
It seems like in the latest maude update, some floating point values changed slightly. This caused chandra_aca tests to fail. This PR changes those tests so floating point values are checked using `np.isclose(a, b)` instead of `a == b`.
- [n/a] Functional testing
Fixes #
=> Fix tests after changes in maude

.gitignore, chandra_aca/maude_decom.py, chandra_aca/tests/test_all.py, chandra_aca/tests/test_maude_decom.py
This makes the following changes:
- cast `packet['IMGTYPE']` as int in _group_packets (it was a string in real-time)
- the `blobs` argument to `get_aca_packets` was ignored. Fixed.
- the result of `get_aca_packets` did not include the `INTEG` and `END_INTEG_TIME ` columns if the times were not shifted to match level0 times (shifting times used to be the default in aca_view until now).
Fixes #127 
None
No functional testing.
=> Fixed maude_decom to work on real-time

chandra_aca/maude_decom.py, chandra_aca/tests/test_maude_decom.py
Unfortunately, I found yet another issue with blobs in maude_decom. This issue does not affect anything I have done up to now.
The `maude_decom.get_raw_aca_blobs` takes a `maude_result` argument, which contains the blobs as returned by maude, and this object is (inadvertently) modified inside the function. As a result, if one tries to use the blobs after calling this function, the data structure has changed and this causes errors. I would prefer to keep the argument unchanged, because whatever changes the function made are implementation details.
One could argue that the modified blobs are a better, because each blob's values are transformed from a list to a dictionary, which is better to fish out specific MSIDs. Namely, the master version does the following:
```
for b in …
```
=> Bugfix: make sure maude_result argument to get_raw_aca_blobs is not modified inside the function

chandra_aca/maude_decom.py, chandra_aca/tests/test_maude_decom.py
This is a trivial change in maude_decom.
When calling get_aca_packets using blobs, it currently sets the image function from `AOACFCT{slot}`, which is the MSID for the image function in the OBC. After this PR, it will set it from `{pea_prefix}AIMGF{slot}1`.
One reason to keep the OBC value is that it is sampled **much** more often, but then it does not match the image shown, so this can cause confusion. I do not remember if we explicitly decided to keep that one. If wed wanted that, I still think this is not the place to do it (because this is all about ACA packets).
Another option is to not have a single image function, but include all four instances of IMGFUN found in ACA telemetry.
None
Unit tests pass, including a new test that would fail in current master.
Independent check of unit …
=> fix in maude_decom.get_aca_packets from blobs

.github/workflows/flake8.yml, chandra_aca/drift.py
Use public copy of file if local not available
Fixes #125 (doesn't add table to ska data but makes it accessible)
Sets the code to use a public version of the file which is a benign change with no impact for the user except they will be able to run the code without access to ICXC.
On laptop without VPN and the code in master:
```
In [1]: from chandra_aca.drift import get_default_zero_offset_table
In [2]: get_default_zero_offset_table()
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/git/chandra_aca/chandra_aca/drift.py in get_default_zero_offset_table()
196     try:
--> 197         CACHE['ZERO_OFFSET_TABLE'] = Table.read(
198 …
```
=> Use a public copy of zero offset aimpoint file if local not available

.github/workflows/black.yml, .pre-commit-config.yaml
This updates the pre-commit hooks for black and isort to use the latest releases. Not that crucial but I just wanted to test the [pre-commit autoupdate](https://pre-commit.com/#pre-commit-autoupdate) machinery.
I also noticed that the black workflow is running on `push` and `pull-request` and this seems to run twice for the initial pull request. So I just changed it to run on `push`.
None
No code changes. The update occurred as expected and was reflected in the commit for this change.
=> Update pre-commit hooks and black workflow to latest versions

chandra_aca/aca_image.py, chandra_aca/tests/test_maude_decom.py, chandra_aca/tests/test_psf.py
Fix deprecations etc for ska3-prime.
`pytest chandra_aca` on Mac was successful with no reported warnings at the end.
Also, tested `ACAImage.__dir__()` by creating an `ACAImage` object and then using IPython <tab> completion to see the expected custom attributes.
=> Remove deprecated decorator and six dependency

chandra_aca/aca_image.py, chandra_aca/planets.py, chandra_aca/tests/test_maude_decom.py, chandra_aca/transform.py
The current sparkles unit test on masters (ska3-prime) has the following warning at the end:
```
sys:1: ResourceWarning: unclosed file <_io.BufferedReader name='/export/jgonzale/github-workflows/miniconda3/envs/ska3-masters-prime/lib/python3.10/site-packages/chandra_aca/data/de432s.bsp'>
```
This is caused by `chandra_aca.planets.load_kernel`, which opens a file that is never closed. This PR adds a cleanup function to fix that.
None
I ran sparkles unit test using this branch and this silenced the warning.
=> fix in planets.py: cleanup jplephem.spk.SPK at exit

chandra_aca/maude_decom.py, chandra_aca/tests/test_maude_decom.py
Image telemetry can be used to download engineering data. In this case `IMGTYPE==3`. MAUDE is smart enough to recognize that the corresponding pixel MSIDs are not present whenever `IMGTYPE==3`, and the MSIDs are not present in the blob. This in turn causes an empty list to be assigned to a pixel array, and an exception being raised with the following error:
```
ValueError: shape mismatch: value array of shape (0,) could not be broadcast to indexing result of shape (16,)
```
When data comes from frames, the pixels have non-zero values corresponding with the data in telemetry, but they are all masked. If the data comes from blobs, the pixels values are zero and are masked.
None
I added a unit test for this case. There was already a test from frames, I just added it for blobs.
This issue …
=> Prevent crash when IMGTYPE==3 when using blobs

chandra_aca/star_probs.py, chandra_aca/tests/test_star_probs.py
This adds a new function to get provenance information about the default acquisition probability model (subject to environment variables). This is intended to be used in proseco to add this info to the star catalogs pickle file.
Adds new function `get_default_acq_prob_model_info`.
In a dev Ska environment with https://github.com/sot/ska_helpers/pull/36 installed.
Independent check of unit tests by Jean
No functional testing. (but there is a new unit test to cover the new functionality)
=> Add function to get default acq prob model info

chandra_aca/star_probs.py, chandra_aca/tests/test_star_probs.py
This updates the function to get the acq probability model (from chandra_models) to cache using `chandra_models_cache` from https://github.com/sot/ska_helpers/pull/36.
None
In a dev Ska environment with https://github.com/sot/ska_helpers/pull/36 installed.
Independent check of unit tests by Jean
No functional testing.
=> Use chandra_models_cache for caching not lru_cache

chandra_aca/star_probs.py, chandra_aca/tests/test_maude_decom.py
In default usage @jeanconn noted that `get_grid_func_model` was being called once with `get_grid_func_model()` and once with `get_grid_func_model(None)`, thus requiring two reads of the model file. This fixes that.
None
```
In [1]: from chandra_aca import star_probs
In [2]: %time model = star_probs.get_grid_func_model()
CPU times: user 23.5 ms, sys: 24.6 ms, total: 48.2 ms
Wall time: 82.8 ms
In [3]: %time model = star_probs.get_grid_func_model(None)
CPU times: user 27 µs, sys: 5 µs, total: 32 µs
Wall time: 34.8 µs
In [4]: %time model = star_probs.get_grid_func_model("grid-*")
CPU times: user 20.4 ms, sys: 18.4 ms, total: 38.8 ms
Wall time: 68.2 ms
```
=> Improve caching performance by adjusting default call pattern

chandra_aca/aca_image.py, chandra_aca/attitude.py, chandra_aca/centroid_resid.py, chandra_aca/dark_model.py, chandra_aca/drift.py, chandra_aca/maude_decom.py, chandra_aca/planets.py, chandra_aca/plot.py, chandra_aca/star_probs.py, chandra_aca/transform.py, docs/conf.py, docs/dark_model.rst, docs/index.rst
This uses some WIP code (https://github.com/sot/skare3_tools/pull/101) to convert from [ReST format](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html) docstrings to [numpydocs](https://numpydoc.readthedocs.io/en/latest/example.html) format. I spent some time trying to use the `pyment` package but found that it does not handle any docstring with inline examples.
The ReST format which is used in most Ska packages is unsatisfactory because it does not really support indicating the type of input parameters.
Rendered sphinx docs: https://icxc.harvard.edu/aspect/test_review_outputs/chandra_aca/pr156/html/
None
Docs were built using this and are available at the URL in the description.
=> Convert docstrings to numpydocs format and add dark_model API docs

chandra_aca/drift.py, chandra_aca/tests/test_drift.py
Add a function, get_fid_offset, to determine the expected y and z offsets of the fid lights from their positions, relative to the fid positions expected from the FEB07 fid characteristics (used in proseco and starcheck) and the current aimpoint drift model (which was last updated after the 2022:094 safe mode).
For functional testing, there is a new unit test and this notebook shows the use of the new offsets reduces the fid residuals on historical data.
https://cxc.cfa.harvard.edu/mta/ASPECT/ipynb/chandra_aca_fid_offset/check_fid_offset.html
=> Add fid offset support to drift

chandra_aca/drift.py, chandra_aca/tests/test_drift.py
Support fid drift times before 2012:001.  This is handled by just clipping the times to the range of the aimpoint drift model.
This may not be needed even for old regression loads, but without a change, the fid offset code would do this:
```
In [2]: get_fid_offset('2010:001', -14)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 1
----> 1 get_fid_offset('2010:001', -14)
File ~/git/chandra_aca/chandra_aca/drift.py:205, in get_fid_offset(time, t_ccd)
200 drift_z = AcaDriftModel(**DRIFT_PARS["dz"])
202 # Compute the predicted asol DY/DZ based on time and ACA CCD temperature
203 # via the predictive model calibrated in the fit_aimpoint_drift notebook
204 # in this repo.  And …
```
=> Support fid drift times before 2012:001

chandra_aca/planets.py, chandra_aca/tests/test_maude_decom.py
This is part of the changes to kadi, chandra_aca, ska_sun, Quaternion, and Chandra.Maneuver to make kadi command states faster.
This change is to use `convert_time_format` in place of `CxoTime` or `DateTime`. Some slight re-ordering of code logic was needed but the changes should be fairly understandable.
This PR also avoids using astropy units in this context. While units are nice and elegant, regular floats / np.arrays are much faster.
Independent check of unit tests by Jean
About a factor of two for these cases.
Setup:
```
>>> from chandra_aca.planets import get_planet_eci, get_planet_angular_sep
>>> from cxotime import CxoTime
>>> times = CxoTime("2023:001").secs + np.linspace(0, 1000, 100)
```
Flight:
```
>>> %timeit dat = get_planet_eci("mars", times)
823 µs ± 15.5 µs per loop (mean …
```
=> Performance improvements for planets

chandra_aca/star_probs.py, chandra_aca/tests/test_star_probs.py
The current acq probability model only extends to mag=10.75 while proseco will choose stars up to 11.0. This creates many warnings which we routinely ignore.
This PR just accepts that we are currently ignoring those warnings and makes them actually go away. Making a new model that samples up to 11.0 is a fairly substantial undertaking and the time scale for doing it is uncertain. When we do that we can back out this change.
Removes warnings.
```
(ska3) ➜  chandra_aca git:(allow-grid-model-extrapolation) git rev-parse HEAD
7d6134e5486f3a54ffff8057579ad94a507d4652
(ska3) ➜  chandra_aca git:(allow-grid-model-extrapolation) pytest chandra_aca  
==================================================== test session starts ====================================================
platform darwin -- …
```
=> Add tolerance args to clip_and_warn

chandra_aca/aca_image.py, chandra_aca/tests/test_aca_image.py
This PR does two things
- Ensure that the `row0` and `col0` attributes are correct for certain indexing/slicing operations
- Raise `IndexError` for out-of-bounds index values. Previously a result was returned but it was wrong.
Fixes #168
```
(ska3) ➜  chandra_aca git:(fix-indexing-issues) ✗ git rev-parse HEAD          
81957d9277b286e1a08a003ae3bd82bce4807457
(ska3) ➜  chandra_aca git:(fix-indexing-issues) pytest
===================================================== test session starts =====================================================
platform darwin -- Python 3.10.8, pytest-7.2.1, pluggy-1.0.0
rootdir: /Users/aldcroft/git, configfile: pytest.ini
plugins: timeout-2.1.0, anyio-3.6.2
collected 204 items …
```
=> Fix indexing issues

chandra_aca/aca_image.py, chandra_aca/maude_decom.py, chandra_aca/tests/test_aca_image.py
This PRs fixes issues found in python 3.11 (Speedy):
- ellipsis is not supported in slicing `ACAImage`
- a warning is issued in maude_decom when casting integer arrays (#166)
**NOTE**: while working on this, I found some unrelated issues I have not fixed. in this PR
Fixes #166 
Fixes #165 
Independent check of unit tests by @taldcroft
No functional testing.
=> [Speedy]: fix ellipsis in ACAImage and squash warning about integer arrays

chandra_aca/plot.py
This fixes an issue where stars from AGASC 1.8 are nearly all plotted in the orange-ish color denoting a star that is not selectable as an acq star. This is currently manifested in starcheck review star catalog plots, making it somewhat difficult to evaluate the star field and catalog.
- https://github.com/sot/proseco/pull/399
- The filtering mask in proseco requires two new AGASC columns compared to the previous `chandra_aca.plot` code: `MAG_ACA` and `COLOR1`.
- The filtering in proseco is somewhat different from the previous code, so there will be changes in the color of plotted stars. In general the changes are for the better and accurately reflect what proseco is using in star selection.
Independent check of unit tests by Jean
```
ska3-jeanconn-fido> export …
```
=> Use proseco acq candidate mask for ACA plot (bad_acq_stars)

.pre-commit-config.yaml, chandra_aca/star_probs.py, chandra_aca/tests/test_star_probs.py
Add binomial uncertainty interval to `star_probs.py`
This notebook: [coverage.ipynb](https://icxc.cfa.harvard.edu/aspect/test_review_outputs/chandra_aca/pr-171/coverage.html)
=> Binomial uncertainty

chandra_aca/maude_decom.py, chandra_aca/tests/test_maude_decom.py
Use CxoTime.linspace on get_aca_images for > 3hour range
This is a possible and trivial implementation of @taldcroft 's thought at https://github.com/sot/chandra_aca/pull/174#issuecomment-2363997248 
This allows stop - start > 3 hours for the get_aca_images method.
This requires cxotime https://github.com/sot/cxotime/pull/44
```
(ska3-flight-latest) flame:chandra_aca jean$ git rev-parse HEAD
3bcd3afc612953f4d6c4ac4e1206afecc032f8b5
(ska3-flight-latest) flame:chandra_aca jean$ pytest
============================================================ test session starts =============================================================
platform darwin -- Python 3.11.8, pytest-8.0.2, pluggy-1.4.0
PyQt5 5.15.9 -- Qt runtime 5.15.8 -- Qt compiled 5.15.8 …
```
=> Use CxoTime.linspace on get_aca_images for > 3hour range

chandra_aca/maude_decom.py
Migrate `maude_decom.py` to use CxoTime throughout and use recommended idioms for time delta arithmetic.
This also makes some improvements in docstrings. It accidentally includes an update that was intended for #181.
- `cxotime` with `CxoTime.linspace()`
- Based off the `maude-aca-chunks` branch.
```
(ska3) ➜  docs git:(maude-use-cxotime) git rev-parse HEAD                                                               
374506ed1b5d85e48b5b16d701affbd30ffdbe0b
(ska3) ➜  docs git:(maude-use-cxotime) env PYTHONPATH=/Users/aldcroft/git/cxotime pytest
========================================================= test session starts ==========================================================
platform darwin -- Python 3.11.8, pytest-7.4.4, pluggy-1.4.0
rootdir: /Users/aldcroft/git
configfile: …
```
=> Migrate maude_decom to CxoTime

chandra_aca/maude_decom.py, chandra_aca/tests/test_maude_decom.py
Change `get_aca_images()` so that it converts the `MaskedColumn` columns from `get_aca_packets` to `Column` if there are no masked elements. 
The only columns that can actually be missing are: 'BGDRMS', 'TEMPCCD', 'TEMPHOUS', 'TEMPPRIM', 'TEMPSEC', 'BGDSTAT'. These columns are not present in 4x4 images, so any query that includes 4x4 images will have these masked.
The 'IMG' column is still always masked because the mask has a slightly different meaning, namely providing the data mask for 4x4 and 6x6 images.
Functional testing with kalman_watch showed a problem with #181, namely that merging (`vstack`) of image tables with a `times` metadata caused warnings:
```
WARNING: Attribute `times` of type <class 'cxotime.cxotime.CxoTime'> cannot be added to FITS Header - skipping …
```
=> `get_aca_images()` returns MaskedColumns only for data with masked values (except IMG)

.pre-commit-config.yaml, chandra_aca/aca_image.py, chandra_aca/dark_subtract.py, chandra_aca/tests/test_aca_image.py, chandra_aca/tests/test_dark_subtract.py, docs/dark_subtract.rst, docs/index.rst
Add some convenience routines to get dark-current background subtracted ACA images.
This depends on https://github.com/sot/mica/pull/301 and https://github.com/sot/mica/pull/311 .
```
(ska3-flight-latest) flame:chandra_aca jean$ git rev-parse HEAD
6e20ccf80970ac9dad70a01e4008a5381d108d0c
(ska3-flight-latest) flame:chandra_aca jean$ python -c "import mica; print(mica.__version__)"
4.37.1.dev2+g8c56ac2
(ska3-flight-latest) flame:chandra_aca jean$ pytest
======================================================================= test session starts =======================================================================
platform darwin -- Python 3.11.8, pytest-8.0.2, pluggy-1.4.0
PyQt5 5.15.9 -- Qt runtime 5.15.8 -- Qt compiled 5.15.8
plugins: …
```
=> Add some routines to get background subtracted images

chandra_aca/tests/test_planets.py
This is a change intended for skare3 > 2025.0, where we will use astropy 7.0. It replaces uses of `Table.pformat_all()` wih `Table.pformat()`. This silences a warning.
```
(ska3-flight-2025.0rc5) ~/SAO/git/chandra_aca pformat $ pytest chandra_aca
============================================================= test session starts =============================================================
rootdir: /Users/javierg/SAO/git
collected 230 items                                                                                                                           
chandra_aca/tests/test_aca_image.py .................. …
```
=> replace uses of pformat_all with pformat

chandra_aca/aca_image.py, chandra_aca/tests/test_dark_subtract.py
Change the get_aca_images default to bgsub=False
Tested in a recent 2025.0 test env.
```
(2025.0) flame:chandra_aca jean$ git rev-parse HEAD
5181dde2a01fceeb1396402b124576fcf7245c13
(2025.0) flame:chandra_aca jean$ pytest
========================================================== test session starts ==========================================================
collected 230 items                                                                                                                     
chandra_aca/tests/test_aca_image.py ..................                                                                            [  7%] …
```
=> Change the get_aca_images default to bgsub=False

.pre-commit-config.yaml, chandra_aca/drift.py, chandra_aca/tests/test_drift.py
This adds a new optional kwarg `drift_pars`to the `get_aca_offsets` and `get_fid_offset` functions. This makes it easier to develop and functionally test a new drift model without having to put that model into branch of `chandra_models`.
New kwarg.
```
(ska3) ➜  chandra_aca git:(add-drift-pars-kwargs) git rev-parse --short HEAD
df74975
(ska3) ➜  chandra_aca git:(add-drift-pars-kwargs) pytest -s                 
=================================================================== test session starts ===================================================================
rootdir: /Volumes/git
collected 250 items …
```
=> Add drift_pars kwarg to get_aca_offsets and get_fid_offset

chandra_aca/aca_image.py, chandra_aca/dark_subtract.py, chandra_aca/tests/test_aca_image.py
In chandra_aca.aca_images.get_aca_images, don't fetch ccd temperature if bgsub=False.
The ccd temperature is only used if bgsub=True and since before this fix the fetching was happening even if bgsub=False, that required a minimum of 30 samples for the default get_tccd_data with default smoothing.  And none of this was coming back in useful error messages if the user tried to fetch a smaller set of images with bgsub=False.
```
----> 1 images = get_aca_images(start=CxoTime(date) - 30 * u.s,
2 stop=CxoTime(date), source="maude")
...
ValueError: Input vector needs to be bigger than window size.
```
This changes the name of the keyward argument in get_tccd_data from "maude_channel" to "channel" to match the kwarg used in other methods.
```
(ska3-latest) flame:chandra_aca jean$ git rev-parse …
```
=> Don't fetch ccd temperature if bgsub=False

chandra_aca/tests/test_aca_image.py
Change time range in short image test.
I'm not really sure why this test passed for the original PR and does not pass now without changing the test, but perhaps the MAUDE data was not stable in the interval.
Fixes #192 
```
(ska3-latest) flame:chandra_aca jean$ pytest
========================================================================================== test session starts ===========================================================================================
collected 252 items …
```
=> Change time range in short image test

chandra_aca/dark_subtract.py, chandra_aca/tests/test_aca_image.py, chandra_aca/tests/test_dark_subtract.py
Fix bug quoting the maude channel for cheta.fetch
```
(ska3-latest) flame:chandra_aca jean$ git rev-parse HEAD
101b9923c5d4e8da53e5444e10d0a18f76e04ae6
(ska3-latest) flame:chandra_aca jean$ pytest
==================================================================== test session starts =====================================================================
collected 254 items                                                                                                                                          
chandra_aca/tests/test_aca_image.py ..................... …
```
=> Fix bug quoting the maude channel for cheta.fetch

chandra_aca/aca_image.py, chandra_aca/tests/test_aca_image.py, ruff-base.toml
Add IMGSIZE to maude aca images
Adds new column to images returned via get_aca_images .
```
(ska3-latest) flame:chandra_aca jean$ git rev-parse HEAD
07d892b9a20feb0dc4ae8a3261d36abfcef74e43
(ska3-latest) flame:chandra_aca jean$ pytest
===================================================================== test session starts =====================================================================
plugins: socket-0.7.0, anyio-4.7.0, timeout-2.3.1
collected 254 items                                                                                                                                           
chandra_aca/tests/test_aca_image.py ..................... …
```
=> Add IMGSIZE to maude aca images
